version: '3.8'

secrets:
  mongodb_username:
    file: ./secrets/mongodb_username.txt
  mongodb_password:
    file: ./secrets/mongodb_password.txt

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    secrets:
      - mongodb_username
      - mongodb_password
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    secrets:
      - mongodb_username
      - mongodb_password
    environment:
      - MONGODB_URI=mongodb://$(cat /run/secrets/mongodb_username):$(cat /run/secrets/mongodb_password)@mongodb:27017/obras?authSource=admin
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongodb_data:
